language: r
env:
  global:
    - AUTHOR_EMAIL=mika.br@gmail.com
    - secure: "aSf4OtQxv+mm9IqqHFLFrFmTMjLF6YBOeyAPcFt6rxN3EeEmAapLDuPjoD75OCTr/4HbD7844zNODs/Hsy8WcUWbluFK2I6Q3kJQOB8MThFsubFwIegbEC6TshYx2zH9tDL3RztWr581hheXpW3Nm8E6yjUOgeJfswtqo12kjSfJRKXa/qnt3j+La5XARB69pnnj8or1RdzloGBwjjTOcmk7n8gKVnEifcaUGLEha6bQZKe/ioJhLOalLFGcy8Wj1VogUFYhCZ3nGhK/fYf5sp+Hl2uKGVNhKS/sEgtRqWxsDUL5BiUshNaafzh53Ss9KXb0wXRV5FosRyW/mj0LhycR5l7NsgarMuS+rFEeJBy0cvJMDxzBnfw7QQ+aiCb7uTxAvqRym+ATe+awWWpXAFZ2okNs+VfdjMAvR42HoniyLgijMf25d+dXPgFF1P3rt6iUY511r6XJWB8+0+rHfQ1W8rU1SRyFBUgLjNyPcoflfpfHIv6/okG23bS28VGu/woM07F4S0TkhbUzJ3Zk9TIWg+1be/vIdzCpIQERwNECBxFoTo1edNooBROiZ2TZ6b44WuCeLZv5TdssgGJsZ+hcRSVapxw7rRVPWJ5gud6wu11af2yufNCd4rfxyjOM1bCwuyqQb7jHcT83eHZO6VQDp+efDkV0Jy50eRqeg9A="
before_install:
  - cd testpackage
after_success:
  - chmod 755 ../.push_gh_pages.sh
  - ../.push_gh_pages.sh
